/**
 * Alle Record-Typen, die das Backend (PowerDNS) erlaubt – für Dropdowns (Zone, Vorlagen).
 * Reihenfolge: häufig zuerst, dann alphabetisch / DNSSEC / Spezial.
 */
export const ALL_RECORD_TYPE_KEYS = [
    'SOA',
    'NS',
    'A',
    'AAAA',
    'CNAME',
    'ALIAS',
    'DNAME',
    'MX',
    'TXT',
    'SPF',
    'SRV',
    'HTTPS',
    'SVCB',
    'CAA',
    'PTR',
    'TLSA',
    'SSHFP',
    'LOC',
    'NAPTR',
    'DS',
    'DNSKEY',
    'NSEC',
    'NSEC3',
    'NSEC3PARAM',
    'RRSIG',
    'OPENPGPKEY',
]

/** Kurze Platzhalter für Vorlagen-Zeile (Ziel-Feld) */
export const TEMPLATE_CONTENT_PLACEHOLDERS = {
    A: '93.184.216.34',
    AAAA: '2001:db8::1',
    CNAME: 'example.com.',
    ALIAS: 'target.example.com.',
    DNAME: 'other.example.',
    MX: 'mail.example.com.',
    TXT: 'v=spf1 include:_spf.example.com ~all',
    SPF: 'v=spf1 ...',
    NS: 'ns1.example.com.',
    SRV: '10 5 443 server.example.com.',
    HTTPS: '0 pool.example.net. alpn=h2',
    SVCB: '0 pool.example.net.',
    CAA: '0 issue "letsencrypt.org"',
    PTR: 'host.example.com.',
    TLSA: '3 1 1 abcdef...',
    SSHFP: '4 2 abcdef...',
    LOC: '50 7 30.0 N 8 40 50.0 E 10m',
    NAPTR: '100 10 "S" "SIP+D2U" "!^.*$!sip:..."',
    DS: '12345 8 2 abcd...',
    DNSKEY: '256 3 8 AwEAA...',
    NSEC: 'next.example.com. A RRSIG NSEC',
    NSEC3: '1 0 1 abcd... A RRSIG',
    NSEC3PARAM: '1 0 1 abcd...',
    RRSIG: 'A 8 3 3600 ...',
    OPENPGPKEY: 'mQCNAz...',
    SOA: 'ns1.example.com. hostmaster.example.com. ...',
}
